generated: '2026-08-12'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: instaagent.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Sep 23 05:37:01 2026 GMT
  hsts: true
  hsts_max_age: 31556926
domains:
- domain: instaagent.com
  dnssec: false
  caa:
  - 0 issuewild "ssl.com"
  - 0 iodef "mailto:kyle@instaagent.com"
  - 0 issue "comodoca.com"
  - 0 issue "digicert.com; cansignhttpexchanges=yes"
  - 0 issue "letsencrypt.org"
  - 0 issue "pki.goog; cansignhttpexchanges=yes"
  spf: true
  dmarc: true
  dmarc_policy: none
